name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore PROG6221.sln
    - name: Build
      run: dotnet build PROG6221.sln --configuration Release --no-restore
